common:
  ATR_N: 14
  EMA_fast: 5
  EMA_slow: 20
  vol_z_period: 30

SOJR:
  or_window_min: 12
  confirm_window_min: 20
  sweep_atr_mult: 1.3
  max_sweep_atr: 4.0
  wick_min: 0.75
  sl_atr_mult: 1.0
  atr_trail_mult: 1.0
  time_stop_min: 60
  rr_min: 1.2
  patch_filter: "loose"
  patch_tol_min: 2
