fx:
  london_open: [{start: "03:00", end: "04:00"}]
  ny_open:     [{start: "08:00", end: "09:00"}]
  overlap:     [{start: "08:00", end: "11:00"}]
patch_marks:
  minutes: [7, 13, 27, 41, 53]
  tolerance_min: 2
